# Generated by Django 4.0.3 on 2023-01-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_remove_automobilevo_color_remove_automobilevo_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
