# Generated by Django 4.0.3 on 2023-01-24 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobilevo_is_sold_alter_automobilevo_import_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='is_sold',
            new_name='sold',
        ),
    ]
