# Generated by Django 4.0.3 on 2023-02-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_rename_is_sold_automobilevo_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='picture_url',
            field=models.URLField(null=True),
        ),
    ]
