# Generated by Django 4.0.3 on 2023-02-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_automobilevo_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='picture_url',
        ),
    ]
