# Generated by Django 4.0.3 on 2023-01-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='technician',
            new_name='technician_name',
        ),
    ]
