# Generated by Django 4.0.3 on 2023-01-25 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_service_technician_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='technician_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_rest.technician'),
        ),
        migrations.AlterField(
            model_name='service',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_rest.autosvo'),
        ),
    ]
