# Generated by Django 4.0.3 on 2023-01-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_service_technician_name_alter_service_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='technician_name',
            new_name='technician',
        ),
    ]
