# Generated by Django 4.0.3 on 2023-01-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_service_date_alter_service_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='time',
        ),
        migrations.AddField(
            model_name='service',
            name='date_time',
            field=models.DateTimeField(default='2023-12-12T12:12'),
            preserve_default=False,
        ),
    ]
