# Generated by Django 4.0.3 on 2023-01-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_autosvo_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
