# Generated by Django 4.0.3 on 2023-01-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_service_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autosvo',
            name='vip',
        ),
    ]
